-- ------------------------------------------------------------------------------
--  Author: Paula Farebrother
--  References:
--      Tutor: Stefan Binder
--      Module: Databases
--      University: Abertay
--  29-03-2024 (created)
--  06-10-2024 (last modified)
-- ------------------------------------------------------------------------------

drop table Employee cascade constraints;
drop table Supervisor cascade constraints;
drop table SupervisedEmployee cascade constraints;
drop table DependChild cascade constraints;
drop table WorkProject cascade constraints;
drop table WorkAllocation cascade constraints;
drop table RoleManager cascade constraints;
drop table Department cascade constraints;
drop table ProjectLocation cascade constraints;
drop table DeptEmployee cascade constraints;
drop table Customer cascade constraints;
drop table Product cascade constraints;
drop table CustomerOrder cascade constraints;
drop table Warehouse cascade constraints;
drop table Inventory cascade constraints;
drop table NIrandoms cascade constraints;
drop table Salarytest ;

create table Employee (
    EmployeeID number generated by default on null as identity,
    constraint EmpIDPK primary key (EmployeeID) enable,
    FirstName varchar2(25 char) constraint FirstNameNN not null enable,
    LastName varchar2(50 char) constraint LastNameNN not null enable,
    NINumber varchar2(12 char),
    EmpAddress varchar2(1000 char) constraint AddressNN not null enable,
    Salary number constraint SalaryNN not null enable,
    SalaryTax number,
    DoB date constraint DoBNN not null enable,
    Email varchar2(100 char) constraint EmailNN not null enable,
    constraint EmailUniq unique (Email) enable,
    ContactNumber varchar2(20 char) constraint ContactNumNN not null enable,
    AltContactNumber varchar2(12 char),
    StartDate date constraint StartDateNN not null enable,
    LeavingDate date
);

create table Supervisor (
    SupervisorID number generated by default on null as identity,
    constraint SupervisorIDPK primary key (SupervisorID) enable,
    EmployeeID references Employee,
    SupervisorStartDate date, -- constraint SupervStartNN not null enable, 
    -- commented out for initial insertion of data
    SupervisorEndDate date
);

create table SupervisedEmployee (
  EmployeeID references Employee,
  SupervisorID references Supervisor
  -- constraint supervisedPK primary key (EmployeeID, SupervisorID)
  -- commented out as causing issues when populating table with data
);

create table DependChild (
    DependChildID number generated by default on null as identity,
    constraint DepChIDPK primary key (DependChildID) enable,
    EmployeeID references Employee,
    FirstName varchar2(25 char) constraint ChildFirstNameNN not null enable,
    LastName varchar2(50 char),
    DoB date constraint ChildDoBNN not null enable,
    Dep_Phone_Number varchar2(20 char),
    Dep_Alt_Number varchar2(20 char),
    ReltoEmp varchar2(50 char)
);

create table WorkProject (
    ProjectID number generated by default on null as identity,
    constraint WProjIDPK primary key (ProjectID) enable,
    ProjectName varchar2(50 char) constraint ProjectNameNN not null enable,
    ProjectStartDate date constraint ProjectStartNN not null enable,
    ProjectEndDate date
);

create table WorkAllocation (
    EmployeeID references Employee,
    ProjectID references WorkProject,
    -- constraint allocationPK primary key (EmployeeID, ProjectID), as above
    DateofWork date constraint DateofWorkNN not null enable,
    HoursWorked number
);

create table RoleManager (
    ManagerID number generated by default on null as identity,
    constraint ManagerIDPK primary key (ManagerID) enable,
    EmployeeID references Employee,
    ManagerStartDate DATE constraint ManagerStartNN not null enable,
    ManagerEndDate DATE
);

create table Department (
    DeptID number generated by default on null as identity,
    constraint DeptIDPK primary key (DeptID) enable,
    ManagerID references RoleManager,
    DeptName varchar2(50 char) constraint DeptNameNN not null enable
);

create table ProjectLocation (
    LocationID number generated by default on null as identity,
    constraint LocationIDPK primary key (LocationID) enable,
    DeptID references Department,
    ProjectID references WorkProject,
    LocationName varchar2(100 char) constraint LocationNameNN not null enable
);

create table DeptEmployee (
    EmployeeID references Employee,
    DeptID references Department,
    constraint DeptEmployeePK primary key (EmployeeID, DeptID),
    DeptEmpStartDate date,
    DeptEmpEndDate date
);

create table Customer (
    CustomerID number generated by default on null as identity,
    constraint CustomerIDPK primary key (CustomerID),
    EmployeeID references Employee,
    CustFirstName varchar2(50 char) constraint CustFNameNN not null enable,
    CustLastName varchar2(50 char) constraint CustLNameNN not null enable,
    CustAddress varchar2(200 char) constraint CustAddressNN not null enable,
    CustTelNum varchar2(20 char) constraint CustTelNN not null enable
);

create table Product (
    ProductID number generated by default on null as identity,
    constraint ProductIDPK primary key (ProductID),
    ProductName varchar2(200 char) constraint ProductNameNN not null enable,
    ProductPrice number constraint ProductPriceNN not null enable
);

create table CustomerOrder (
    CustOrderID number generated by default on null as identity,
    constraint CustOrderIDPK primary key (CustOrderID),
    CustomerID references Customer,
    TransacDate date constraint TransacDateNN not null enable,
    PayMethod varchar2(20 char) constraint PayMethodNN not null enable
);

create table CustOrdLineItem (
    LineItemID number generated by default on null as identity,
    constraint LineItemIDPK primary key (LineItemID),
    CustOrderID references CustomerOrder,
    ProductID references Product,
    Quantity number constraint QuantityNN not null enable
);

create table Warehouse (
    WarehouseID number generated by default on null as identity,
    constraint WarehouseIDPK primary key (WarehouseID),
    WHName varchar2(100 char) constraint WHNameNN not null enable,
    WHCapacity number constraint WHCapacityNN not null enable,
    WHLocation varchar2(200 char) constraint WHLocationNN not null enable
);

create table Inventory (
    InventoryID number generated by default on null as identity, -- added as PK removed below
    constraint InventoryIDPK primary key (InventoryID),
    WarehouseID references Warehouse,
    ProductID references Product,
    -- constraint InventoryPK primary key (WarehouseID, ProductID) 
    -- commented out as causing issue with inserting data
    StockLevel number constraint StockLevelNN not null enable
);

-- Additional tables for creating random data
-- table for NI Number random generation
create table NIrandoms ( 
    letters varchar2 (2),
    numbers number (6),
    letter varchar2 (1),
    NINumber varchar2(12 char)
) ;

-- Additional constraint added
alter table SupervisedEmployee
add constraint unique_supervised_employee unique (EmployeeID, SupervisorID);

-- To hold data for WorkProject Table once generated
create table WorkProjData (
    ProjectName varchar(30 char) -- Adjust data type and size if needed
);

-- Data table created to prepare for CustomerOrder table
create table CusOrdData (
    CustomerID number,
    ProductID  number,
    TransacDate date default sysdate,
    PayMethod varchar2( 25 char)
);

-----------------------------------------------------------------------------
--                     Additional Tables Utilising PL/SQL                  --
-----------------------------------------------------------------------------

-- Created data for testing using PL/SQL
create table Salarytest as
select *
from (
select 1 Salary, 2 as expected_result from dual union
select 27500, 1375 from dual union
select 64800, 5184 from dual union
select 72700, 5816 from dual union
select 16500, 330 from dual union
select 46700, 3736 from dual
) ;
